# Generated by Django 5.1.6 on 2025-03-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='picture',
        ),
    ]
