# Generated by Django 5.1.6 on 2025-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_remove_trainee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='picture',
            field=models.ImageField(null=True, upload_to='trainee/pictures'),
        ),
    ]
