# Generated by Django 5.1.6 on 2025-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
