# Generated by Django 4.1.7 on 2025-03-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
        ('trainee', '0005_trainee_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='track.tracks'),
        ),
    ]
