# Generated by Django 4.1.7 on 2025-03-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('track', '0001_initial'),
        ('trainee', '0006_alter_trainee_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='track.tracks'),
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='courses',
        ),
        migrations.AddField(
            model_name='trainee',
            name='courses',
            field=models.ManyToManyField(related_name='trainees', to='course.courses'),
        ),
    ]
