# Generated by Django 4.1.7 on 2025-03-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0007_trainee_track_remove_trainee_courses_trainee_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='picture',
            new_name='img',
        ),
    ]
