# Generated by Django 5.1.6 on 2025-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hours', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='courses/pictures')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
